name: Install Dependencies

# Trigger the workflow on push or pull request to the 'main' branch (or your default branch)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out the repository code to the runner

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python in the environment
        with:
          python-version: '3.12'  # Use the correct version of Python for your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Verify dependencies installation
        run: |
          pip list  # List installed packages to verify that dependencies are installed
